/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import configtool.MainForm;
import datalayer.DoterraDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajpap
 */
public class ItemPanel extends javax.swing.JPanel {
    DoterraDB db;
    /**
     * Creates new form ItemPanel
     */
    public ItemPanel(DoterraDB db) {
        this.db = db;
        initComponents();
    }
    
    public void loadItems(JComboBox jbox)
    {
        String str = (String) jbox.getSelectedItem();
        ResultSet rs = db.getItems(str);
        Vector<String> columnNames = new Vector<>();
        Vector<Vector<Object>> dataVector = new Vector<>();
        try
        {
        int columnCount = rs.getMetaData().getColumnCount();

        // Column names.

        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            columnNames.add(rs.getMetaData().getColumnName(columnIndex));
        }

        // Data of the table.
        while (rs.next()) {
            Vector<Object> rowVector = new Vector<>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                rowVector.add(rs.getObject(columnIndex));
            }
            dataVector.add(rowVector);
        }
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultTableModel dtm = new DefaultTableModel(dataVector, columnNames);
        jTable1.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(800, 250));
        setMinimumSize(new java.awt.Dimension(800, 250));
        setPreferredSize(new java.awt.Dimension(800, 250));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
